#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Sitecore.Data;
using Sitecore.Globalization;

namespace AddressValidation.PageContent.Models
{
    public partial interface IGlassBase
    {		
        [SitecoreId]
        Guid Id { get; }		

        [SitecoreInfo(SitecoreInfoType.Language)]
        Language Language { get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        string Url { get; }
	
        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        Guid TemplateId { get; }       
    }

    public abstract partial class GlassBase : IGlassBase
    {		
        [SitecoreId]
        public virtual Guid Id { get; private set; }		

        [SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

        [SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

        [SitecoreInfo(SitecoreInfoType.TemplateId)]
        public virtual Guid TemplateId { get; private set; }
    }

    /// <summary>
    /// IAddressValidation Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/Validation/Address Validation</para>	
    /// <para>ID: 79847fd6-4851-433a-b30c-82b098f3c1bf</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAddressValidationConstants.TemplateIdString, Cachable = false)]
    public partial interface IAddressValidation : IGlassBase 
    {
			
        /// <summary>
        /// The Address line 1 field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: d767c8e5-bc59-49e3-a930-6d34296257eb</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.AddressLine1FieldName)]
        string AddressLine1 { get; set; }
			
			
        /// <summary>
        /// The Address line 2 field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: b2511f83-13f2-428c-bca1-92e88169e791</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.AddressLine2FieldName)]
        string AddressLine2 { get; set; }
			
			
        /// <summary>
        /// The City field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: b2a884ca-d9ee-48bc-a9dc-2c00d105c78f</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.CityFieldName)]
        string City { get; set; }
			
			
        /// <summary>
        /// The Country field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: f2b94f07-6f1f-4098-9d2e-6339da08f264</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.CountryFieldName)]
        string Country { get; set; }
			
			
        /// <summary>
        /// The State field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 6b590d93-cd44-4771-9cf1-25347406ef37</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.StateFieldName)]
        string State { get; set; }
			
			
        /// <summary>
        /// The ZipCode field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 1a19280e-10ec-436a-88a7-62cfff7be999</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.ZipCodeFieldName)]
        string ZipCode { get; set; }
			
			
        /// <summary>
        /// The CSS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: f96a8c93-ff21-4291-9c51-c7f225332246</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.CSSFileLinkFieldName)]
        string CSSFileLink { get; set; }
			
			
        /// <summary>
        /// The JS file Link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 98d41e93-fb13-4b29-89ef-53e9d700259c</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IAddressValidationConstants.JSFileLinkFieldName)]
        string JSFileLink { get; set; }
			
			
    }


    public static partial class IAddressValidationConstants{

        public const string TemplateIdString = "79847fd6-4851-433a-b30c-82b098f3c1bf";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "Address Validation";

		
			
        public static readonly ID AddressLine1FieldId = new ID("d767c8e5-bc59-49e3-a930-6d34296257eb");
        public const string AddressLine1FieldName = "Address line 1";
			
		
			
        public static readonly ID AddressLine2FieldId = new ID("b2511f83-13f2-428c-bca1-92e88169e791");
        public const string AddressLine2FieldName = "Address line 2";
			
		
			
        public static readonly ID CityFieldId = new ID("b2a884ca-d9ee-48bc-a9dc-2c00d105c78f");
        public const string CityFieldName = "City";
			
		
			
        public static readonly ID CountryFieldId = new ID("f2b94f07-6f1f-4098-9d2e-6339da08f264");
        public const string CountryFieldName = "Country";
			
		
			
        public static readonly ID StateFieldId = new ID("6b590d93-cd44-4771-9cf1-25347406ef37");
        public const string StateFieldName = "State";
			
		
			
        public static readonly ID ZipCodeFieldId = new ID("1a19280e-10ec-436a-88a7-62cfff7be999");
        public const string ZipCodeFieldName = "ZipCode";
			
		
			
        public static readonly ID CSSFileLinkFieldId = new ID("f96a8c93-ff21-4291-9c51-c7f225332246");
        public const string CSSFileLinkFieldName = "CSS file link";
			
		
			
        public static readonly ID JSFileLinkFieldId = new ID("98d41e93-fb13-4b29-89ef-53e9d700259c");
        public const string JSFileLinkFieldName = "JS file Link";
			
			

    }

	
    /// <summary>
    /// AddressValidation
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/Validation/Address Validation</para>	
    /// <para>ID: 79847fd6-4851-433a-b30c-82b098f3c1bf</para>	
    /// </summary>
    [SitecoreType(TemplateId = IAddressValidationConstants.TemplateIdString, Cachable = false)] 
    public partial class AddressValidation : GlassBase, IAddressValidation 
    {
	   
		
        /// <summary>
        /// The Address line 1 field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: d767c8e5-bc59-49e3-a930-6d34296257eb</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.AddressLine1FieldName)]
        public virtual string AddressLine1 { get; set; }
					
		
        /// <summary>
        /// The Address line 2 field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: b2511f83-13f2-428c-bca1-92e88169e791</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.AddressLine2FieldName)]
        public virtual string AddressLine2 { get; set; }
					
		
        /// <summary>
        /// The City field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: b2a884ca-d9ee-48bc-a9dc-2c00d105c78f</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.CityFieldName)]
        public virtual string City { get; set; }
					
		
        /// <summary>
        /// The Country field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: f2b94f07-6f1f-4098-9d2e-6339da08f264</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.CountryFieldName)]
        public virtual string Country { get; set; }
					
		
        /// <summary>
        /// The State field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 6b590d93-cd44-4771-9cf1-25347406ef37</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.StateFieldName)]
        public virtual string State { get; set; }
					
		
        /// <summary>
        /// The ZipCode field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 1a19280e-10ec-436a-88a7-62cfff7be999</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.ZipCodeFieldName)]
        public virtual string ZipCode { get; set; }
					
		
        /// <summary>
        /// The CSS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: f96a8c93-ff21-4291-9c51-c7f225332246</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.CSSFileLinkFieldName)]
        public virtual string CSSFileLink { get; set; }
					
		
        /// <summary>
        /// The JS file Link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 98d41e93-fb13-4b29-89ef-53e9d700259c</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IAddressValidationConstants.JSFileLinkFieldName)]
        public virtual string JSFileLink { get; set; }
					
			
    }

    /// <summary>
    /// IEmailValidation Interface
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/Validation/Email Validation</para>	
    /// <para>ID: d406ae84-aa10-4ad3-b6de-b7e571bded89</para>	
    /// </summary>
    [SitecoreType(TemplateId = IEmailValidationConstants.TemplateIdString, Cachable = false)]
    public partial interface IEmailValidation : IGlassBase 
    {
			
        /// <summary>
        /// The CSS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 636c7b60-da61-42bf-b812-af00c0308429</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IEmailValidationConstants.CSSFileLinkFieldName)]
        string CSSFileLink { get; set; }
			
			
        /// <summary>
        /// The JS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 839a7af7-5722-4f80-a884-e4e9520f47b2</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IEmailValidationConstants.JSFileLinkFieldName)]
        string JSFileLink { get; set; }
			
			
        /// <summary>
        /// The Email field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 5b7dbe55-7ab8-43a5-9245-9f45be15cabe</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [SitecoreField(IEmailValidationConstants.EmailFieldName)]
        string Email { get; set; }
			
			
    }


    public static partial class IEmailValidationConstants{

        public const string TemplateIdString = "d406ae84-aa10-4ad3-b6de-b7e571bded89";
        public static readonly ID TemplateId = new ID(TemplateIdString);
        public const string TemplateName = "Email Validation";

		
			
        public static readonly ID CSSFileLinkFieldId = new ID("636c7b60-da61-42bf-b812-af00c0308429");
        public const string CSSFileLinkFieldName = "CSS file link";
			
		
			
        public static readonly ID JSFileLinkFieldId = new ID("839a7af7-5722-4f80-a884-e4e9520f47b2");
        public const string JSFileLinkFieldName = "JS file link";
			
		
			
        public static readonly ID EmailFieldId = new ID("5b7dbe55-7ab8-43a5-9245-9f45be15cabe");
        public const string EmailFieldName = "Email";
			
			

    }

	
    /// <summary>
    /// EmailValidation
    /// <para></para>
    /// <para>Path: /sitecore/templates/Feature/Validation/Email Validation</para>	
    /// <para>ID: d406ae84-aa10-4ad3-b6de-b7e571bded89</para>	
    /// </summary>
    [SitecoreType(TemplateId = IEmailValidationConstants.TemplateIdString, Cachable = false)] 
    public partial class EmailValidation : GlassBase, IEmailValidation 
    {
	   
		
        /// <summary>
        /// The CSS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 636c7b60-da61-42bf-b812-af00c0308429</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IEmailValidationConstants.CSSFileLinkFieldName)]
        public virtual string CSSFileLink { get; set; }
					
		
        /// <summary>
        /// The JS file link field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 839a7af7-5722-4f80-a884-e4e9520f47b2</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IEmailValidationConstants.JSFileLinkFieldName)]
        public virtual string JSFileLink { get; set; }
					
		
        /// <summary>
        /// The Email field.
        /// <para></para>
        /// <para>Field Type: Single-Line Text</para>		
        /// <para>Field ID: 5b7dbe55-7ab8-43a5-9245-9f45be15cabe</para>
        /// <para>Custom Data: </para>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
        [SitecoreField(IEmailValidationConstants.EmailFieldName)]
        public virtual string Email { get; set; }
					
			
    }
}